import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { StrictMode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          footer: 'hidden', // remove sign up link in the login page
        },
      }}
    >
      <StrictMode>
        <html lang="en" className="h-full bg-white">
          <body className="h-full" suppressHydrationWarning={true}>
            {children}
          </body>
        </html>
      </StrictMode>
    </ClerkProvider>
  )
}
